# --- Enable gpio ---
CONFIG_GPIO=y

# --- Use internal clock ---
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# --- Logging ---
# To enable logging, keep these set to 'n'
CONFIG_SERIAL=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
# To enable logging, set these to 'y'
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_PROCESS_THREAD=n



CONFIG_HWINFO=y